---
name: data-and-insights-wepi
on:
  push:
    branches: 
      - dih/develop
    paths:
      - 'terraform/environments/data-and-insights-wepi/**'
      - '.github/workflows/data-and-insights-wepi.yml'
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'terraform/environments/data-and-insights-wepi/**'
      - '.github/workflows/data-and-insights-wepi.yml'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
defaults:
  run:
    shell: bash

jobs:
  
  # Temp job to untaint Redshift cluster
  untaint-redshift-dev:
    name: Untaint Redshift cluster
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: "~1"
          terraform_wrapper: false
      - name: Terraform untaint - development
        run: |
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
          terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
          terraform -chdir="terraform/environments/data-and-insights-wepi" untaint aws_redshift_cluster.wepi_redshift_cluster
        env:
          TF_ENV: development
  
#  # These jobs run when creating a pull request
#  plan-development:
#    name: Plan Development - data-and-insights-wepi
#    runs-on: ubuntu-latest
#    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2.3.4
#      - name: Load and Configure Terraform
#        uses: hashicorp/setup-terraform@v1.3.2
#        with:
#          terraform_version: "~1"
#          terraform_wrapper: false
#      - name: Terraform plan - development
#        run: |
#          echo "Terraform plan - ${TF_ENV}"
#          bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
#          terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
#          bash scripts/terraform-plan.sh terraform/environments/data-and-insights-wepi
#        env:
#          TF_ENV: development
#
#  deploy-development:
#    name: Deploy Development - data-and-insights-wepi
#    runs-on: ubuntu-latest
#    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#    environment:
#      name: data-and-insights-wepi-development
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2.3.4
#      - name: Load and Configure Terraform
#        uses: hashicorp/setup-terraform@v1.3.2
#        with:
#          terraform_version: "~1"
#          terraform_wrapper: false
#      - name: Terraform apply - development
#        run: |
#          echo "Terraform apply - ${TF_ENV}"
#          bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
#          terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
#          bash scripts/terraform-apply.sh terraform/environments/data-and-insights-wepi
#        env:
#          TF_ENV: development
#
#   plan-test:
#     name: Plan Test - data-and-insights-wepi
#     runs-on: ubuntu-latest
#     if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2.3.4
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform plan - test
#         run: |
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
#           terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/data-and-insights-wepi
#         env:
#           TF_ENV: test

#   deploy-test:
#     name: Deploy Test - data-and-insights-wepi
#     runs-on: ubuntu-latest
#     if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#     environment:
#       name: data-and-insights-wepi-test
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2.3.4
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform apply - test
#         run: |
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
#           terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/data-and-insights-wepi
#         env:
#           TF_ENV: test

#   # These jobs run after merging to main
#   plan-preproduction:
#     name: Plan Preproduction - data-and-insights-wepi
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2.3.4
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform plan - preproduction
#         run: |
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
#           terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/data-and-insights-wepi
#         env:
#           TF_ENV: preproduction

#   deploy-preproduction:
#     name: Deploy Preproduction - data-and-insights-wepi
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     environment:
#       name: data-and-insights-wepi-preproduction
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2.3.4
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform apply - preproduction
#         run: |
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
#           terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/data-and-insights-wepi
#         env:
#           TF_ENV: preproduction
  
#   plan-production:
#     name: Plan Production - data-and-insights-wepi
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2.3.4
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform plan - production
#         run: |
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
#           terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/data-and-insights-wepi
#         env:
#           TF_ENV: production

#   deploy-production:
#     name: Deploy Production - data-and-insights-wepi
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     environment:
#       name: data-and-insights-wepi-production
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2.3.4
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform apply - production
#         run: |
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/data-and-insights-wepi
#           terraform -chdir="terraform/environments/data-and-insights-wepi" workspace select "data-and-insights-wepi-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/data-and-insights-wepi
#         env:
#           TF_ENV: production
