---
name: tariff
on:
  push:
    branches: 
      - main
    paths:
      - 'terraform/environments/tariff/**'
      - '.github/workflows/tariff.yml'
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'terraform/environments/tariff/**'
      - '.github/workflows/tariff.yml'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
defaults:
  run:
    shell: bash

jobs:
  
  # These jobs run when creating a pull request
  plan-development:
    name: Plan Development - tariff
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: "~1"
          terraform_wrapper: false
      - name: Terraform plan - development
        run: |
          terraform --version
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/tariff
          terraform -chdir="terraform/environments/tariff" workspace select "tariff-${TF_ENV}"
          bash scripts/terraform-plan.sh terraform/environments/tariff
        env:
          TF_ENV: development

  deploy-development:
    name: Deploy Development - tariff
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment:
      name: tariff-development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: "~1"
          terraform_wrapper: false
      - name: Terraform apply - development
        run: |
          terraform --version
          echo "Terraform apply - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/tariff
          terraform -chdir="terraform/environments/tariff" workspace select "tariff-${TF_ENV}"
          bash scripts/terraform-apply.sh terraform/environments/tariff
        env:
          TF_ENV: development

#   plan-test:
#     name: Plan Test - tariff
#     runs-on: ubuntu-latest
#     if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v2.0.0
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform plan - test
#         run: |
#           terraform --version
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/tariff
#           terraform -chdir="terraform/environments/tariff" workspace select "tariff-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/tariff
#         env:
#           TF_ENV: test

#   deploy-test:
#     name: Deploy Test - tariff
#     runs-on: ubuntu-latest
#     if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#     environment:
#       name: tariff-test
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v2.0.0
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform apply - test
#         run: |
#           terraform --version
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/tariff
#           terraform -chdir="terraform/environments/tariff" workspace select "tariff-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/tariff
#         env:
#           TF_ENV: test

#   # These jobs run after merging to main
#   plan-preproduction:
#     name: Plan Preproduction - tariff
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v2.0.0
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform plan - preproduction
#         run: |
#           terraform --version
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/tariff
#           terraform -chdir="terraform/environments/tariff" workspace select "tariff-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/tariff
#         env:
#           TF_ENV: preproduction

#   deploy-preproduction:
#     name: Deploy Preproduction - tariff
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     environment:
#       name: tariff-preproduction
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v2.0.0
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform apply - preproduction
#         run: |
#           terraform --version
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/tariff
#           terraform -chdir="terraform/environments/tariff" workspace select "tariff-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/tariff
#         env:
#           TF_ENV: preproduction
  
#   plan-production:
#     name: Plan Production - tariff
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v2.0.0
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform plan - production
#         run: |
#           terraform --version
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/tariff
#           terraform -chdir="terraform/environments/tariff" workspace select "tariff-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/tariff
#         env:
#           TF_ENV: production

#   deploy-production:
#     name: Deploy Production - tariff
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     environment:
#       name: tariff-production
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v2.0.0
#         with:
#           terraform_version: "~1"
#           terraform_wrapper: false
#       - name: Terraform apply - production
#         run: |
#           terraform --version
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/tariff
#           terraform -chdir="terraform/environments/tariff" workspace select "tariff-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/tariff
#         env:
#           TF_ENV: production
