---
name: testing
on:
  push:
    branches: 
      - main
    paths:
      - 'terraform/environments/testing/**'
      - '.github/workflows/testing.yml'
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'terraform/environments/testing/**'
      - '.github/workflows/testing.yml'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
defaults:
  run:
    shell: bash

jobs:
  
  # These jobs run when creating a pull request
#   plan-development:
#     name: Plan Development - testing
#     runs-on: ubuntu-latest
#     if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: 1.0.1
#           terraform_wrapper: false
#       - name: Terraform plan - development
#         run: |
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/testing
#           terraform -chdir="terraform/environments/testing" workspace select "testing-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/testing
#         env:
#           TF_ENV: development

#   deploy-development:
#     name: Deploy Development - testing
#     runs-on: ubuntu-latest
#     if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#     environment:
#       name: testing-development
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: 1.0.1
#           terraform_wrapper: false
#       - name: Terraform apply - development
#         run: |
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/testing
#           terraform -chdir="terraform/environments/testing" workspace select "testing-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/testing
#         env:
#           TF_ENV: development
          
  plan-test:
    name: Plan Test - testing
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform plan - test
        run: |
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/testing
          terraform -chdir="terraform/environments/testing" workspace select "testing-${TF_ENV}"
          bash scripts/terraform-plan.sh terraform/environments/testing
        env:
          TF_ENV: test

  deploy-test:
    name: Deploy Test - testing
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment:
      name: testing-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform apply - test
        run: |
          echo "Terraform apply - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/testing
          terraform -chdir="terraform/environments/testing" workspace select "testing-${TF_ENV}"
          bash scripts/terraform-apply.sh terraform/environments/testing
        env:
          TF_ENV: test

  # These jobs run after merging to main
#   plan-preproduction:
#     name: Plan Preproduction - testing
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: 1.0.1
#           terraform_wrapper: false
#       - name: Terraform plan - preproduction
#         run: |
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/testing
#           terraform -chdir="terraform/environments/testing" workspace select "testing-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/testing
#         env:
#           TF_ENV: preproduction

#   deploy-preproduction:
#     name: Deploy Preproduction - testing
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     environment:
#       name: testing-preproduction
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: 1.0.1
#           terraform_wrapper: false
#       - name: Terraform apply - preproduction
#         run: |
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/testing
#           terraform -chdir="terraform/environments/testing" workspace select "testing-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/testing
#         env:
#           TF_ENV: preproduction
  
#   plan-production:
#     name: Plan Production - testing
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: 1.0.1
#           terraform_wrapper: false
#       - name: Terraform plan - production
#         run: |
#           echo "Terraform plan - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/testing
#           terraform -chdir="terraform/environments/testing" workspace select "testing-${TF_ENV}"
#           bash scripts/terraform-plan.sh terraform/environments/testing
#         env:
#           TF_ENV: production

#   deploy-production:
#     name: Deploy Production - testing
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     environment:
#       name: testing-production
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3.0.2
#       - name: Load and Configure Terraform
#         uses: hashicorp/setup-terraform@v1.3.2
#         with:
#           terraform_version: 1.0.1
#           terraform_wrapper: false
#       - name: Terraform apply - production
#         run: |
#           echo "Terraform apply - ${TF_ENV}"
#           bash scripts/terraform-init.sh terraform/environments/testing
#           terraform -chdir="terraform/environments/testing" workspace select "testing-${TF_ENV}"
#           bash scripts/terraform-apply.sh terraform/environments/testing
#         env:
#           TF_ENV: production
